Traceback (most recent call last):
  File "/Users/nce8/opt/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/nce8/opt/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nce8/opt/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nce8/opt/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nce8/opt/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/nce8/opt/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/nce8/opt/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load a dataset of Trump tweets from 
setwd("/users/nick/github/computational_methods_boot_camp/source/data")

# These are saved in a format called JSON, 
# so we need to import than with a json package 
# and then convert them to a dataframe:

library(rjson)
json_data <- fromJSON(file="trump_tweets.json")
tweet_data <- do.call("rbind", lapply(json_data, as.data.frame))

# Columns for subsetting
names(tweet_data)
------------------


[0;36m  Cell [0;32mIn[1], line 10[0;36m[0m
[0;31m    tweet_data <- do.call("rbind", lapply(json_data, as.data.frame))[0m
[0m                                                     ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


